/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page.Homepage;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import net.miginfocom.swing.MigLayout;
import page.Homepage.ChatComponent.ChatBody;
import page.Homepage.ChatComponent.ChatBottom;
import page.Homepage.ChatComponent.ChatTitle;
import page.Homepage.ChatComponent.SingleTonBodyChat;

/**
 *
 * @author trunk
 */
public class Chat extends javax.swing.JPanel {
    
//    private ChatBody chatBody = new ChatBody();
//    private ChatBottom chatBottom = new ChatBottom();
    /**
     * Creates new form RightPanel
     */
    public Chat() {
        initComponents();
        init();
        
        
    }
    
    private void init(){
        this.setLayout(new MigLayout("fillx", "0[fill]0", ""));
        ChatTitle chatTitle = new ChatTitle();
        ChatBody chatBody = SingleTonBodyChat.getBodyChat();
        ChatBottom chatBottom = new ChatBottom();
        this.add(chatTitle, "wrap");
        this.add(chatBody, "wrap");
        this.add(chatBottom, "wrap");
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(763, 694));
        setName(""); // NOI18N
        setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
