/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package page.Homepage;

import GraphBase.Graph;
import GraphBase.UserVertex;
import components.Item_AddPerson;
import components.Item_Person;
import dao.GraphOfConnectionData;
import dao.UserDAO;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import model.Session;
import model.User;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author trunk
 */
public class Search extends javax.swing.JPanel {

    /**
     * Creates new form RightPanel
     */
    public Search() {
        initComponents();
        init();
    }

    private void init() {
        listPerson.setLayout(new MigLayout());
        showPeople();
    }

    UserDAO userDAO = new UserDAO();

    private void showPeople() {
        int userId = Session.getUserID();
        GraphOfConnectionData graphOfConnectionData = new GraphOfConnectionData();
        String sessionUserRegion = userDAO.getUserRegion(userId, graphOfConnectionData);

        List<Item_AddPerson> listPerson = new ArrayList<>();

        for (UserVertex userVertex : graphOfConnectionData.graph.getVertices()) {
            if (userVertex.id != userId) {
                if (!graphOfConnectionData.graph.checkConnection(graphOfConnectionData.graph.getUser(userId), userVertex)) {
                    listPerson.add(new Item_AddPerson(userVertex.firstName + " " + userVertex.lastName, userVertex.id));
                }
            }
        }

        listPerson.sort(new Comparator<Item_AddPerson>() {
            @Override
            public int compare(Item_AddPerson o1, Item_AddPerson o2) {
                String region1 = userDAO.getUserRegion(o1.id, graphOfConnectionData);
                String region2 = userDAO.getUserRegion(o2.id, graphOfConnectionData);
                int weight1 = graphOfConnectionData.getWeight(sessionUserRegion, region1);
                int weight2 = graphOfConnectionData.getWeight(sessionUserRegion, region2);
                return Integer.compare(weight1, weight2);
            }
        });

        for (Item_AddPerson person : listPerson) {
            addPersonToUI(person);
        }
    }
    private void addPersonToUI(Item_AddPerson person) {
        
        listPerson.add(person, "wrap");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPerson = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(236, 694));
        setMinimumSize(new java.awt.Dimension(236, 694));

        listPerson.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout listPersonLayout = new javax.swing.GroupLayout(listPerson);
        listPerson.setLayout(listPersonLayout);
        listPersonLayout.setHorizontalGroup(
            listPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        listPersonLayout.setVerticalGroup(
            listPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listPerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane listPerson;
    // End of variables declaration//GEN-END:variables
}
