/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import ChatService.ChatClient;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Session;
import page.Homepage.Chat;

import page.Homepage.ChatComponent.ChatBody;
import page.Homepage.ChatComponent.ChatBottom;
import page.Homepage.ChatComponent.ChatTitle;

import page.Homepage.ChatComponent.SingleTonChatBottom;
import page.Homepage.ChatComponent.SingleTonChatTitle;
import page.Homepage.Home;


/**
 *
 * @author ADMIN
 */
public class Item_Person extends javax.swing.JPanel {
    
    /**
     * Creates new form Item_Person
     */
    public int id;
    private ChatClient chatClient;
    public String userName;

    public Item_Person(String name, int id) {
        this.id = id;
        this.userName = name;
        initComponents();
        lb.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new components.ImageAvatar();
        lb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        imageAvatar1.setAlignmentX(1.0F);
        imageAvatar1.setAlignmentY(1.0F);
        imageAvatar1.setBorderSize(2);
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icon/avt.png"))); // NOI18N
        imageAvatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageAvatar1MouseClicked(evt);
            }
        });
        imageAvatar1.setLayout(new javax.swing.BoxLayout(imageAvatar1, javax.swing.BoxLayout.LINE_AXIS));

        lb.setBackground(new java.awt.Color(255, 255, 255));
        lb.setText("Name");
        lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMouseClicked
        // TODO add your handling code here:
        formMouseClicked(evt);
    }//GEN-LAST:event_lbMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        ChatBody chatBody = Home.chat.getBody();
        chatBody.currentUserId = this.id;
        chatBody.loadText(this.id, Session.getUserID());
        
        
        
        
        // setting chat bottom
        ChatBottom chatBottom = SingleTonChatBottom.getBottomChat(); 
        chatBottom.button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                chatClient = Home.chatClient;
                String text = chatBottom.txt.getText().trim();
                if(!text.isEmpty()){
                    chatBody.addItemRight(text);
                    chatBottom.txt.setText("");
                    // save text to db
                    
                    /* phan nay dung de test, tham so truyen vao khong duoc co dinh nhu the nao, tham so truyen vao la userID va FriendID */
                    chatBottom.saveTextToDB(text, Session.getUserID(), id);
                    
                    chatClient.sendMessage(id + " " + text + " " + Session.getUserID());
                    /**/
                    
                    chatBottom.txt.grabFocus();
                    
                    
                    
                }else{
                    chatBottom.txt.grabFocus();
                }
            }
            
        });
        
        
        
        
        // setting chattitle
        ChatTitle chatTitle = SingleTonChatTitle.getChatTitle();
        
        chatTitle.setUsername(userName);
        
        
    }//GEN-LAST:event_formMouseClicked

    private void imageAvatar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar1MouseClicked
        // TODO add your handling code here:
        formMouseClicked(evt);
    }//GEN-LAST:event_imageAvatar1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.ImageAvatar imageAvatar1;
    private javax.swing.JLabel lb;
    // End of variables declaration//GEN-END:variables
}
